[package]
name = "lg"
version = "0.1.0"
authors = ["ESC <youhavethewrong@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
hyper = "0.13"
serde = "1.0"
serde_derive = "1.0"
tokio = { version = "0.2", features = ["full"] }
toml = "0.5"
